workflows:
  flutter-ios-workflow:
    name: Flutter iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: 3.29.3
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install Flutter dependencies
        script: |
          cd /Users/builder/clone
          flutter pub get
      - name: Flutter build ipa
        script: |
          cd /Users/builder/clone
          flutter clean
          flutter build ipa --release
    # Code signing configuration for App Store distribution
    ios_signing:
      distribution_type: app_store  # Force App Store distribution (not Development)
      bundle_id: com.freshducky.myrentrange
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - kevon@example.com  # Update with your email
        notify:
          success: true
          failure: false
      slack:
        notify:
          success: true
          failure: true

  flutter-android-workflow:
    name: Flutter Android Workflow
    max_build_duration: 120
    instance_type: linux_x2
    environment:
      flutter: 3.29.3
      java: 17
    scripts:
      - name: Install Flutter dependencies
        script: |
          cd /home/builder/clone
          flutter pub get
      - name: Flutter build apk
        script: |
          cd /home/builder/clone
          flutter clean
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/bundle/**/*.aab
    publishing:
      email:
        recipients:
          - kevon@example.com  # Update with your email
        notify:
          success: true
          failure: false

