workflows:
  flutter-ios-workflow:
    name: Flutter iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Flutter build ipa
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - kevon@example.com  # Update with your email
        notify:
          success: true
          failure: false
      slack:
        notify:
          success: true
          failure: true

  flutter-android-workflow:
    name: Flutter Android Workflow
    max_build_duration: 120
    instance_type: linux_x2
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Flutter build apk
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/bundle/**/*.aab
    publishing:
      email:
        recipients:
          - kevon@example.com  # Update with your email
        notify:
          success: true
          failure: false

