workflows:
  ios-native-workflow:
    name: iOS Native Build
    environment:
      groups:
        - app_store_credentials
      xcode: latest
    scripts:
      - name: Get Flutter packages
        script: |
          cd "OneDrive/Desktop/warm_light_calculator"
          flutter packages pub get
      - name: Build iOS app
        script: |
          cd "OneDrive/Desktop/warm_light_calculator/ios"
          xcode-project build-ipa \
            --project "Runner.xcworkspace" \
            --scheme "Runner" \
            --output-dir "build/ios/ipa"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID

