workflows:
  ios-workflow:
    name: iOS Build
    # Warm Light Calculator CI/CD configuration
    environment:
      groups:
        - app_store_credentials
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          cd "OneDrive/Desktop/warm_light_calculator"
          flutter packages pub get
      - name: Configure Xcode project
        script: |
          cd "OneDrive/Desktop/warm_light_calculator/ios"
          xcode-project use-profiles
      - name: Build iOS IPA
        script: |
          cd "OneDrive/Desktop/warm_light_calculator"
          flutter build ipa --release
    artifacts:
      - OneDrive/Desktop/warm_light_calculator/build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID

