workflows:
  ios-production:
    name: iOS Production Build
    environment:
      groups:
        - app_store_credentials
      xcode: latest
    scripts:
      - name: Build iOS
        script: |
          cd "OneDrive/Desktop/warm_light_calculator"
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID

